
bot_id: '' # Идентификатор вашего бота
log_path: '' # Путь до лог файла
start_text:
  cases: 'Разработай функциональные тестовые кейсы с различными вариациями тестовых данных для требований с применением тест-дизайна:\n'
  api: 'Разработай функциональные тестовые кейсы с различными вариациями тестовых данных для полей по спецификации API с применением тест-дизайна:\n'
  api_curl: 'Сгенерируй несколько CURL запросов с различными вариациями тестовых данных с применением тест-дизайна и напиши ожидаемый результат к каждой проверке для тестов по спецификации open API:\n'
  api_curl_swagger: 'Сгенерируй несколько CURL запросов с различными вариациями тестовых данных с применением тест-дизайна и напиши ожидаемый результат к каждой проверке для тестов по спецификации swagger:\n'
  api_java: 'Трансформируй CURL запросы в api тесты на Java с использованием RestAssured:\n'
  api_python: 'Трансформируй CURL запросы в api тесты на Python с использованием Requests:\n'
  api_pageobject: 'Составь локаторы для html элементов, используя XPATH, на JAVA + Selenide, создаваемые переменные должны быть типа String, по переданной html:\n'
  more_cases: 'Сгенерируй еще дополнительные тестовые кейсы по переданным ранее условиям'
auth:
  gigachat_auth: 'Basic {token}' #Токен базовой авторизации в sber gigachat
  yagpt_oauth: '' # токен авторизации в yandex gpt
  yandexPassportOauthToken: '' # токен авторизации в yandex gpt (аналогичный предыдущему)
  folder_id: '' # folder id в личном кабинете yandexgpt
  yandexgpt_key: '' # Ключ yandexgpt
links:
  gigachat_auth_link: 'https://ngw.devices.sberbank.ru:9443/api/v2/oauth'
  gigachat_gpt_link: 'https://gigachat.devices.sberbank.ru/api/v1/chat/completions'
  jira_link: '' # Ссылка на вашу Jira
  yandex_gpt_api_url: 'https://llm.api.cloud.yandex.net/foundationModels/v1/completion'
  wiki_url: '' # Ссылка на ваш confluence
database:
  pg_host: '' # Адрес вашей БД Postgres
  pg_port: '' # Порт вашей БД Postgres
  pg_database: '' # Имя вашей БД 
  pg_user: '' # Логин вашей БД
  pg_password: '' # Пароль вашей БД